FROM  tensorflow/tensorflow:2.16.1-gpu-jupyter

RUN pip install --upgrade pip 

RUN pip install jupyterlab==4.2.2
RUN pip install pandas
RUN pip install scikit-learn

RUN pip install seaborn
RUN pip install pyfaidx==0.5.9.5
RUN pip install bokeh==2.3.1
RUN pip install shap==0.39.0

RUN pip install biopython
RUN pip install umap-learn 
RUN pip install xlrd
RUN pip install openpyxl
RUN pip install featuretools

RUN pip install lightgbm==2.2.3

RUN pip3 install torch torchvision torchaudio
RUN pip3 install pytorch-lightning

RUN pip install flaml
RUN pip install tensorboard
RUN pip install lifelines