FROM gaarangoa/ml:stable 

#################################################################################################################
#           AI & JUPYTER
#################################################################################################################

RUN pip install --upgrade pip 
RUN pip install pdoc3
RUN pip install mlflow
RUN pip install xlrd
RUN pip install openpyxl
RUN pip install pyfaidx==0.5.9.5
RUN pip install bokeh==2.3.1
RUN pip install seaborn --upgrade
RUN pip install biopython
RUN pip install umap-learn 
RUN pip install scikit-learn==0.23.2
RUN pip install rich==10.1.0
RUN pip install alive-progress==1.6.2
RUN pip install lightgbm==2.2.3

RUN pip install flaml==0.6.2
RUN pip install jupyterlab==3.1.10
RUN pip install shap==0.39.0
RUN pip install mlflow==1.15.0

RUN pip install jupyter-book
RUN pip install lifelines


