FROM python:3.9.6

#################################################################################################################
#  AI v 2.0.2
#################################################################################################################

RUN apt-get update

RUN pip install --upgrade pip 

RUN pip install jupyterlab==3.1.10

RUN pip install pandas --upgrade

RUN pip install scikit-learn==0.24.1
RUN pip install seaborn==0.11.1

RUN pip install xlrd
RUN pip install openpyxl

RUN pip install sqlalchemy
RUN pip install psycopg2
RUN pip install sqlalchemy-redshift

RUN pip install flaml

RUN pip install jupyter-book
RUN pip install lifelines