FROM tensorflow/tensorflow:2.11.0-gpu-jupyter

#################################################################################################################
#  AI v 2.1.0.0
#################################################################################################################

RUN pip install torch torchvision torchaudio
RUN pip install pytorch-lightning

RUN apt-get update

RUN pip install --upgrade pip 
RUN pip install opencv-python==4.5.5.62
RUN pip install jupyterlab==3.2.9
RUN pip install pandas==1.1.5
RUN pip install scikit-learn==0.24.1
RUN pip install seaborn==0.11.1
RUN pip install pyfaidx==0.5.9.5
RUN pip install bokeh==2.3.1
RUN pip install dash==1.20.0
RUN pip install dash dash_bootstrap_components 
RUN pip install shap==0.39.0
RUN pip install featuretools==0.23.3

RUN pip install biopython==1.79
RUN pip install rich
RUN pip install umap-learn==0.5.1
RUN pip install xlrd
RUN pip install openpyxl
RUN pip install pdoc3

RUN pip install lightgbm==3.2.1
RUN pip install mlflow==1.15.0
RUN pip install pandas-profiling[notebook]

RUN pip install flaml==0.6.2
RUN pip install tensorboard

RUN pip install jupyter-book
RUN pip install lifelines==0.26.0

RUN pip install dowhy==0.6
RUN pip install scikit-survival==0.17.0
RUN pip install pysurvival==0.1.2
RUN pip install nevergrad==0.4.3
RUN pip install networkx==2.5.1
RUN pip install gprofiler_official==1.0.0
RUN pip install streamlit==1.2.0
RUN pip install reactpy

RUN pip install transformers

