FROM gaarangoa/ml:stable 

#################################################################################################################
#           AI & JUPYTER
#################################################################################################################

RUN pip install --upgrade pip 
RUN pip install --upgrade torch torchvision 
RUN pip install --upgrade jupyterlab
RUN pip install aquirdturtle_collapsible_headings
RUN pip install pdoc3
RUN pip install mlflow
RUN pip install xlrd
RUN pip install pandas --upgrade 
RUN pip install openpyxl
RUN pip install featuretools
RUN pip install pyfaidx==0.5.9.5
RUN pip install bokeh==2.3.1
RUN pip install seaborn --upgrade