FROM gaarangoa/ml:stable 

#################################################################################################################
#  AI
#################################################################################################################

RUN pip install --upgrade pip 
# RUN pip install --upgrade torch torchvision 

RUN pip install scikit-learn==0.24.1
RUN pip install pandas==1.2.4 
RUN pip install seaborn==0.11.1

RUN pip install mlflow==1.15.0

RUN pip install pyfaidx==0.5.9.5
RUN pip install bokeh==2.3.1
RUN pip install dash==1.20.0
RUN pip install shap==0.39.0

RUN pip install biopython
RUN pip install rich
RUN pip install umap-learn 
RUN pip install xlrd
RUN pip install openpyxl
RUN pip install featuretools
RUN pip install pdoc3
